# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/26-atomic-host"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end
  config.vm.network "private_network", ip: "192.168.99.99"
  config.vm.provision "shell", 
    inline: "docker run --rm -d -p 8080:8080 rancher/server:v2.0.0-alpha8"
end
